name = "R"
uuid = "9bf996c8-9dd4-4e66-b658-56dabb729bde"
authors = ["Affan S <affan.s@outlook.com> and contributors"]
version = "0.1.0"

[compat]
julia = "1.5"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
